### ISSUE TITLE
Validation error for pipeline channel reported to wrong path

### ISSUE THREAD

**Issue by JWahle** [HEnquist/pycamilladsp-plot#6]
[This config](https://github.com/HEnquist/pycamilladsp-plot/files/6418057/wrong_channel.yml.zip) has an invalid channel number in the pipeline section.
The path for the error is `pipeline/0`, but I think, it should be `pipeline/0/channel`.

This leads me to the question, for what items in the config errors might be reported.
If you see the YAML file as a tree, I assumed, that validation errors are only reported for the leafs of the tree, but not for the branches. I also assumed, that there is at most one error per leaf.
With respect to the config snippet below, e.g.:
- for `devices/capture_samplerate`, but not for `devices`
- for `filters/New Filter 1/parameters/freq` but not for `filters`, `filters/New Filter 1` nor `filters/New Filter 1/parameters`
- for `pipeline/0/channel`, but not for `pipeline` or `pipeline/0`

Is that correct?
```
devices:
  capture_samplerate: 44100
filters:
  New Filter 1:
    parameters:
      freq: 1000
      q: 0.5
      type: Lowpass
    type: Biquad
pipeline:
- channel: 3
  names:
  - New Filter 1
  type: Filter
```

**Comment by HEnquist** [comment]
The channel error should definitely be reported as `pipeline/0/channel`, I have fixed that now.

Errors are reported where they are found. When possible, the errors are reported one the leafs. Like here:
```
filters:
  hp_80:
    type: Biquad
    parameters:
      type: Highpass
      freq: -80
      q: -0.5
```
gives:
```
filters/hp_80/parameters/freq  :  -80 is less than or equal to the minimum of 0.0
filters/hp_80/parameters/q  :  -0.5 is less than or equal to the minimum of 0.0
```
I haven't seen any examples where it reports more than one error on a leaf.


If the parameters block itself is invalid, then the error will be reported there:
```
filters:
  hp_80:
    type: Biquad
    parameters:
      type: Highpass
      freq: -80
      qvalue: -0.5
```
gives:
```
Errors:
filters/hp_80/parameters  :  'q' is a required property
filters/hp_80/parameters  :  Additional properties are not allowed ('qvalue' was unexpected)
```
This gives two errors, one that a required values was missing, and one that something extra was found (which isn't allowed).
This kind of errors will likely never happen for configs built by the gui, but very easily when doing it by hand.
