### ISSUE TITLE
Missing validations

### ISSUE THREAD

**Issue by JWahle** [HEnquist/pycamilladsp-plot#8]
I think, [this config](https://github.com/HEnquist/pycamilladsp-plot/files/6445938/validation_errors.yml.zip), has some errors, which should be reported as validation errors:
- devices/playback: invalid additional properties are not reported
- mixers/mixer/channels/in: should be invalid <=0
- mixers/mixer/channels/out: should be invalid <= 0

**Comment by HEnquist** [comment]
Should be fixed now!

**Comment by JWahle** [comment]
The config, that I sent you, was not optimal:
channels.in == 0 and channels.out == 0 should also be reported as invalid.
Currently, this is valid according to pycamilladsp-plot.

**Comment by HEnquist** [comment]
It's actually valid also according to camilladsp itself, but zero channels can never work. Same goes for capture and playback devices. I'll take care of it.

**Comment by HEnquist** [comment]
pycamilladsp-plot is updated to not allow 0-channel mixers now. Playback and capture devices were already ok. Now I'll take a look at camilladsp.

**Comment by HEnquist** [comment]
And fixed in camilladsp too, will be included in 0.5.1.

**Comment by JWahle** [comment]
As far as I am concerned, this is fixed.
I just noticed a little quirk in CDSP - not sure, if you can do much about it, though.
The following config has the error in line 30, but CDSP reports it as being in line 29:
```
devices:
  adjust_period: 1
  capture:
    avoid_blocking_read: false
    channels: 2
    device: hw:0
    format: S32LE
    retry_on_error: false
    type: Alsa
  capture_samplerate: 48000
  chunksize: 1
  enable_rate_adjust: true
  enable_resampling: true
  playback:
    channels: 2
    device: hw:0
    format: S32LE
    type: Alsa
  queuelimit: 1
  resampler_type: FastAsync
  samplerate: 44100
  silence_threshold: 0
  silence_timeout: 1
  target_level: 1
filters: {}
mixers:
  New Mixer 1:
    channels:
      in: 1
      out: 0
    mapping:
    - dest: 0
      mute: false
      sources:
      - channel: 0
        gain: -1
        inverted: false
        mute: false
pipeline: []
```
